config/routes.rb
Rails.application.routes.draw do
  namespace :providers do
    get 'purchases/index'
  end
  get 'admin/index'
  post 'admin/import'
  namespace :api do
    namespace :v1 do
      resources :clients, only: %w(index show)
      resources :providers, only: %w(index)
      resources :products, only: %w(index show)
      resources :orders, only: %w(create)
    end
  end
  resources :price_formulas do
    member do
      get 'toggle'
    end
  end
  resources :freights, only: %w(index)
  resources :reports, only: %w(index)
  resources :orders, only: %w(index show) do
    member do
      get 'toogle_delivered'
    end
  end
  resources :sale_point, only: :index
  resources :inventory, only: :index
  resources :products
  resources :product_brands
  resources :product_categories
  resources :providers do
    resources :provider_contacts 
  end
  resources :clients
  devise_for :users
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, except: :destroy
end

app/views/shared/_header.slim
header.app-header
  .header-notification-container.h-20.flex.items-center.justify-end.gap-12.px-10
    .app-notifications.flex-grow
      p.notice.font-semibold = notice
      p.alert.font-semibold = alert
    div
      svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10 text-yellow-300" fill="none" viewBox="0 0 24 24" stroke="currentColor"
        path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"

    .user-info.grid.items-center
      .text-center
        span.inline-block.bg-blue-900.rounded-lg.p-1
          svg xmlns="http://www.w3.org/2000/svg" class="inline h-8 w-8" viewBox="0 0 20 20" fill="currentColor"
            path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"

      span.font-bold
        = link_to 'Administrador', admin_index_path if current_user.is_admin? 

app/views/shared/_menu.slim
div.app-menu.flex.flex-col.justify-between
  nav.w-72
    .main-menu.flex.flex-col
      .px-5.py-8.bg-white
        = image_tag  image_path 'LogoMM.png', class: 'filter drop-shadow-lg'
    
      ul.flex.flex-col.gap-1.5.text-white.bg-white


        li
          = link_to root_path, class: "px-4 py-3 text-sm flex items-center gap-5 cursor-pointer #{'active' if controller_name == 'home' }" do
            svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"
              path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
            | Inicio

        li
          = link_to sale_point_index_path, class: "px-4 py-3 text-sm flex items-center gap-5 cursor-pointer #{'active' if controller_name == 'sale_point' }" do
            svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"
              path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z"
            | Ventas
        - if controller_name == 'sale_point' || controller_name == 'orders'
          ul.mt-0.5.bg-white
            li.pl-7
              = link_to orders_path, class: "px-4 py-3 text-sm flex items-center gap-5 cursor-pointer #{'active' if controller_name == 'orders' }" do
                svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"
                  path stroke="none" d="M0 0h24v24H0z" fill="none"/
                  line x1="9" y1="6" x2="20" y2="6" /
                  line x1="9" y1="12" x2="20" y2="12" /
                  line x1="9" y1="18" x2="20" y2="18" /
                  line x1="5" y1="6" x2="5" y2="6.01" /
                  line x1="5" y1="12" x2="5" y2="12.01" /
                  line x1="5" y1="18" x2="5" y2="18.01" /
                | Detalles
        li
          = link_to inventory_index_path, class: "px-4 py-3 text-sm flex items-center gap-5 cursor-pointer #{'active' if controller_name == 'inventory' }" do
            svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"
              path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4"
            | Almacén
          
        li
          = link_to providers_path, class: "px-4 py-3 text-sm flex items-center gap-5 cursor-pointer #{'active' if controller_name == 'providers' }" do
            svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"
              path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z"
            | Proveedores

        li
          = link_to clients_path, class: "px-4 py-3 text-sm flex items-center gap-5 cursor-pointer #{'active' if controller_name == 'clients' }" do
            svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"
              path d="M9 6a3 3 0 11-6 0 3 3 0 016 0zM17 6a3 3 0 11-6 0 3 3 0 016 0zM12.93 17c.046-.327.07-.66.07-1a6.97 6.97 0 00-1.5-4.33A5 5 0 0119 16v1h-6.07zM6 11a5 5 0 015 5v1H1v-1a5 5 0 015-5z" /
            | Clientes

        li
          = link_to users_path, class: "px-4 py-3 text-sm flex items-center gap-5 cursor-pointer #{'active' if controller_name == 'users' }" do
            svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"
              path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z"
            | Usuarios

        li
          = link_to reports_path, class: "px-4 py-3 text-sm flex items-center gap-5 cursor-pointer #{'active' if controller_name == 'reports' }" do
            svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"
              path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6"
            | Reportes
        li.px-4.py-3.text-sm.flex.items-center.gap-5.cursor-pointer
          svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"
            path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
          | Cobros & Pagos
        li
          = link_to freights_path, class: "px-4 py-3 text-sm flex items-center gap-5 cursor-pointer #{'active' if controller_name == 'freights' }" do
            svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"
              path stroke="none" d="M0 0h24v24H0z" fill="none"/
              circle cx="7" cy="17" r="2" /
              circle cx="17" cy="17" r="2" /
              path d="M5 17h-2v-11a1 1 0 0 1 1 -1h9v12m-4 0h6m4 0h2v-6h-8m0 -5h5l3 5" /
            | Fletes

  .user-logout.shrink-grow.text-center
    = link_to destroy_user_session_path, method: :delete, class: 'block pb-5' do
      span.icon
        <svg xmlns="http://www.w3.org/2000/svg" class="text-blue-200 bg-blue-600 rounded mr-2 inline icon icon-tabler icon-tabler-power" width="44" height="44" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
          <path d="M7 6a7.75 7.75 0 1 0 10 0" />
          <line x1="12" y1="4" x2="12" y2="12" />
        </svg>
      span.logout-text.text-blue-400.font-bold Cerrar Sesión