config/routes.rb
Rails.application.routes.draw do
  namespace :providers do
    get 'purchases/index'
  end
  get 'admin/index'
  post 'admin/import'
  namespace :api do
    namespace :v1 do
      resources :clients, only: %w(index show)
      resources :providers, only: %w(index)
      resources :products, only: %w(index show)
      resources :orders, only: %w(create)
    end
  end
  resources :price_formulas do
    member do
      get 'toggle'
    end
  end
  resources :freights, only: %w(index)
  resources :reports, only: %w(index)
  resources :orders, only: %w(index show) do
    member do
      get 'toogle_delivered'
    end
  end
  resources :sale_point, only: :index
  resources :inventory, only: :index
  resources :products
  resources :product_brands
  resources :product_categories
  resources :providers do
    resources :provider_contacts 
  end
  resources :clients
  devise_for :users
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, except: :destroy
end

app/models/freight.rb
class Freight < ApplicationRecord
  include PgSearch::Model

  belongs_to :client
  belongs_to :order
  belongs_to :user

  pg_search_scope :search_scope_full,
                  associated_against: {
                    order: :code,
                    user: [:name, :first_surname, :second_surname]
                  },
                  against: [:id],
                  using: {
                    tsearch: {
                      any_word: true
                    },
                    trigram: {
                      threshold: 0.1
                    }
                  }
end

app/controllers/freights_controller.rb
class FreightsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_freight, only: %i[ show edit update destroy ]

  # GET /freights or /freights.json
  def index
    @q = Freight.ransack(params[:q])
    @freights = @q.result(distinct: true)
  end

  # GET /freights/1 or /freights/1.json
  def show
  end

  # GET /freights/new
  # def new
  #   @freight = Freight.new
  # end

  # GET /freights/1/edit
  # def edit
  # end

  # POST /freights or /freights.json
  # def create
  #   @freight = Freight.new(freight_params)
  #   respond_to do |format|
  #     if @freight.save
  #       format.html { redirect_to @freight, notice: "Freight was successfully created." }
  #       format.json { render :show, status: :created, location: @freight }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @freight.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /freights/1 or /freights/1.json
  def update
    respond_to do |format|
      if @freight.update(freight_params)
        format.html { redirect_to @freight, notice: "Freight was successfully updated." }
        format.json { render :show, status: :ok, location: @freight }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @freight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /freights/1 or /freights/1.json
  def destroy
    @freight.destroy
    respond_to do |format|
      format.html { redirect_to freights_url, notice: "Freight was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_freight
      @freight = Freight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def freight_params
      params.require(:freight).permit(:client_id, :kind, :import, :order_id, :user_id)
    end
end

app/helpers/freights_helper.rb
module FreightsHelper
end

app/views/freights/_form.html.slim
= simple_form_for @client, html: { class: 'default' } do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    .flex.mb-2.gap-5
      = f.input :name, label: 'Nombre', wrapper_class: 'flex-1'
      = f.input :first_surname, label: 'Apellido Paterno', wrapper_class: 'flex-1'
      = f.input :second_surname, label: 'Apellido Materno', wrapper_class: 'flex-1'
    .grid.grid-cols-3.mb-2.gap-5
      = f.input :address, label: 'Dirección', wrapper_class: 'col-span-2'
      = f.input :email, label: 'Correo', wrapper_class: 'flex-1'
    .grid.grid-cols-4.mb-2.gap-5
      = f.input :location, label: 'Ciudad'
      = f.input :country, label: 'País', as: :string
      = f.input :postal_code, label: 'Código Postal'
      = f.input :mobile_number, label: 'Número de Telefono Móvil'
      /= f.input :state, label: 'Estado'
    .grid.grid-cols-4.mb-2.gap-5
      = f.input :phone_number, label: 'Número de Telefono Fijo', wrapper_class: 'col-start-4'
  br
  h2.text.lg.font-bold.mb-4 Referencia Aval
  hr.mb-2
  .container.grid.grid-cols-4.gap-x-3
    = f.input :endorsement_full_name, label: 'Nombre Completo', wrapper_class: 'col-span-2'
    = f.input :endorsement_mobile_phone, label: 'Número de Teléfono Móvil'
    = f.input :endorsement_phone_number, label: 'Número de Teléfono Fijo'
    = f.input :endorsement_address, label: 'Dirección', wrapper_class: 'col-span-3'
    = f.input :endorsement_location, label: 'Ciudad'
    = f.input :endorsement_country, label: 'País', as: :string
    = f.input :endorsement_postal_code, label: 'Código Postal'
    = f.input :endorsement_relationship, label: 'Parentesco'

    .form-actions.self-end
      = f.button :submit

app/views/freights/edit.html.slim
.bg-white.m-16.p-5.rounded-lg.shadow.xl:w-3/4.xl:mx-auto
  h1.text-xl.mb-5.font-bold Editando Cliente

  == render 'form'

  => link_to 'Atrás', clients_path
  '|
  =< link_to 'Ver', @client

app/views/freights/index.html.slim
.container.mt-16.mx-16.mb-3
  = search_form_for @q do |f|
    = f.search_field :order_code_cont, placeholder: 'Buscar Flete', class: 'rounded-l-lg'
    = f.submit 'Buscar', class: 'bg-blue-400 text-white px-3 py-2 rounded-r-lg'

.bg-white.mx-16.p-5.rounded-lg.shadow
  h1.text-xl.mb-5.font-bold Lista de Fletes

  /= link_to '+ Nuevo flete', new_freight_path, class: 'float-right bg-green-600 text-white px-3 rounded'
  .container.w-full.overflow-x-auto
    table.w-full.table-fixed
      thead.bg-gray-200
        tr
          th width="120" Flete
          th Cliente
          th Tipo
          th Fecha de registro
          th width="150" Importe
          th width="150" Venta
          th width="150"

      tbody
        - @freights.each do |freight|
          tr
            td.px-5.py-3.text-center = freight.id
            td.px-5.py-3.text-center = freight.client.full_name
            td.px-5.py-3.text-center = freight.kind
            td.px-5.py-3.text-center = freight.created_at
            td.px-5.py-3.text-center = number_to_currency freight.import
            td.px-5.py-3.text-center = freight.order&.code
            td.px-5.py-3.text-center
              div
                = link_to 'Venta', order_path(freight.order), class: 'border-2 border-green-200 px-3 rounded text-green-600'
                /= link_to 'Show', freight
                /=<> "|"
                /= link_to 'Edit', edit_freight_path(freight)
                /=<> "|"
                /= link_to 'Destroy', freight, data: { confirm: 'Are you sure?' }, method: :delete

  br

app/views/freights/new.html.slim
.bg-white.m-16.p-5.rounded-lg.shadow
  h1.text-xl.mb-5.font-bold Agregar Cliente

  == render 'form'

  = link_to 'Back', clients_path

app/views/freights/show.html.slim
.bg-white.m-16.p-5.rounded-lg.shadow
  p
    strong Name:
    = @client.name

  p
    strong First surname:
    = @client.first_surname

  p
    strong Second surname:
    = @client.second_surname

  p
    strong Address:
    = @client.address

  p
    strong Location:
    = @client.location

  p
    strong State:
    = @client.state

  p
    strong Country:
    = @client.country

  p
    strong Postal code:
    = @client.postal_code

  p
    strong Email:
    = @client.email

  p
    strong Mobile number:
    = @client.mobile_number

  p
    strong Phone number:
    = @client.phone_number

  p
    strong Endorsement full name:
    = @client.endorsement_full_name

  p
    strong Endorsement mobile phone:
    = @client.endorsement_mobile_phone

  p
    strong Endorsement phone number:
    = @client.endorsement_phone_number

  p
    strong Endorsement address:
    = @client.endorsement_address

  p
    strong Endorsement location:
    = @client.endorsement_location

  p
    strong Endorsement country:
    = @client.endorsement_country

  p
    strong Endorsement postal code:
    = @client.endorsement_postal_code

  p
    strong Endorsement relationship:
    = @client.endorsement_relationship

  => link_to 'Edit', edit_client_path(@client)
  '|
  =< link_to 'Back', clients_path