config/routes.rb
Rails.application.routes.draw do
  namespace :providers do
    get 'purchases/index'
  end
  get 'admin/index'
  post 'admin/import'
  namespace :api do
    namespace :v1 do
      resources :clients, only: %w(index show)
      resources :providers, only: %w(index)
      resources :products, only: %w(index show)
      resources :orders, only: %w(create)
    end
  end
  resources :price_formulas do
    member do
      get 'toggle'
    end
  end
  resources :freights, only: %w(index)
  resources :reports, only: %w(index)
  resources :orders, only: %w(index show) do
    member do
      get 'toogle_delivered'
    end
  end
  resources :sale_point, only: :index
  resources :inventory, only: :index
  resources :products
  resources :product_brands
  resources :product_categories
  resources :providers do
    resources :provider_contacts 
  end
  resources :clients
  devise_for :users
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, except: :destroy
end

app/models/product_brand.rb
class ProductBrand < ApplicationRecord
  validates :name, presence: true
  has_many :products
  has_many :price_formulas, as: :priceable

  after_create do
    PriceFormulaUpdater.new(self).update
  end
end

app/controllers/product_brands_controller.rb
class ProductBrandsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product_brand, only: %i[ show edit update destroy ]

  # GET /product_brands or /product_brands.json
  def index
    @product_brands = ProductBrand.all
  end

  # GET /product_brands/1 or /product_brands/1.json
  def show
  end

  # GET /product_brands/new
  def new
    @product_brand = ProductBrand.new
  end

  # GET /product_brands/1/edit
  def edit
  end

  # POST /product_brands or /product_brands.json
  def create
    @product_brand = ProductBrand.new(product_brand_params)

    respond_to do |format|
      if @product_brand.save
        format.html { redirect_to @product_brand, notice: "Product brand was successfully created." }
        format.json { render :show, status: :created, location: @product_brand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_brands/1 or /product_brands/1.json
  def update
    respond_to do |format|
      if @product_brand.update(product_brand_params)
        format.html { redirect_to @product_brand, notice: "Product brand was successfully updated." }
        format.json { render :show, status: :ok, location: @product_brand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_brands/1 or /product_brands/1.json
  def destroy
    @product_brand.destroy
    respond_to do |format|
      format.html { redirect_to product_brands_url, notice: "Product brand was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_brand
      @product_brand = ProductBrand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_brand_params
      params.require(:product_brand).permit(:name, :active)
    end
end

app/helpers/product_brands_helper.rb
module ProductBrandsHelper
end

app/views/product_brands/_form.html.slim
= simple_form_for @product_brand, html: { class: 'default' } do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :active

  .form-actions
    = f.button :submit

app/views/product_brands/edit.html.slim
.bg-white.m-16.p-5.rounded-lg.shadow
  h1.text-xl.mb-5.font-bold Editando Marca

  == render 'form'

  => link_to 'Ver', @product_brand
  '|
  =< link_to 'Atrás', product_brands_path

app/views/product_brands/index.html.slim
.bg-white.m-16.p-5.rounded-lg.shadow
  h1.text-xl.mb-5.font-bold Lista de Marcas
  = link_to '+ Nueva Marca', new_product_brand_path, class: 'float-right bg-green-600 text-white px-3 rounded visited:text-white'

  table.w-full.table-fixed
    thead
      tr.bg-gray-200
        th.px-2.text-left Nombre
        th.px-2 Activa
        th.px-2

    tbody
      - @product_brands.each do |product_brand|
        tr
          td.px-2 = product_brand.name
          td.px-2.text-center = product_brand.active ? "Activo" : "Inactivo"
          td.px-2.text-right
            = link_to 'Ver', product_brand
            =<> "|"
            = link_to 'Editar', edit_product_brand_path(product_brand)
            =<> "|"
            = link_to 'Eliminar', product_brand, data: { confirm: 'Are you sure?' }, method: :delete
  br

app/views/product_brands/new.html.slim
.bg-white.m-16.p-5.rounded-lg.shadow
  h1.text-xl.mb-5.font-bold Nueva Marca

  == render 'form'

  = link_to 'Back', product_brands_path

app/views/product_brands/show.html.slim
.bg-white.m-16.p-5.rounded-lg.shadow
  p
    strong Nombre:
    = @product_brand.name

  p
    strong Activa:
    = @product_brand.active

  => link_to 'Editar', edit_product_brand_path(@product_brand)
  '|
  =< link_to 'Atrás', product_brands_path