config/routes.rb
Rails.application.routes.draw do
  namespace :providers do
    get 'purchases/index'
  end
  get 'admin/index'
  post 'admin/import'
  namespace :api do
    namespace :v1 do
      resources :clients, only: %w(index show)
      resources :providers, only: %w(index)
      resources :products, only: %w(index show)
      resources :orders, only: %w(create)
    end
  end
  resources :price_formulas do
    member do
      get 'toggle'
    end
  end
  resources :freights, only: %w(index)
  resources :reports, only: %w(index)
  resources :orders, only: %w(index show) do
    member do
      get 'toogle_delivered'
    end
  end
  resources :sale_point, only: :index
  resources :inventory, only: :index
  resources :products
  resources :product_brands
  resources :product_categories
  resources :providers do
    resources :provider_contacts 
  end
  resources :clients
  devise_for :users
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, except: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model

  belongs_to :provider
  belongs_to :product_brand
  belongs_to :product_category
  has_many :price_formulas, as: :priceable
  has_many :order_items

  validates :code, presence: true
  validates :name, presence: true
  validates :stock, presence: true
  validates :min_stock, presence: true
  validates :list_price, presence: true
  
  before_save :assign_cost_price

  after_create do
    PriceFormulaUpdater.new(self).update
  end

  pg_search_scope :search_scope_full,
                  against: [:code, :name],
                  using: {
                    tsearch: {
                      any_word: true
                    },
                    trigram: {
                      threshold: 0.2
                    }
                  }

  def self.search(params)
    products = self.all.order(name: :asc)
    products = products.search_scope_full(params[:full_data]) if params[:full_data]
    products
  end

  def self.out_of_minimum_stock
    self.all.select(&:is_minimum_stock?)
  end

  def is_minimum_stock?
    self.stock <= self.min_stock
  end

  def all_price_formulas
    PriceFormula.where(provider: provider, priceable: [product_brand, self] ).active
  end

  def brand_price_formulas
    all_price_formulas.where(priceable: product_brand )
  end

  def product_price_formulas
    all_price_formulas.where(priceable: self )
  end

  private

  def assign_cost_price
    self.cost_price = calc_cost_price
  end

  def calc_cost_price
    applyable_price_formulas =
      all_price_formulas.reject{ |pf|
        (pf.priceable_type == 'ProductBrand' && all_price_formulas.where(
            priceable_type: 'Product',
            name: pf.name).count >= 1)}

    list_price + applyable_price_formulas.sum(&:final_value)
  end
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController
  before_action :set_product, only: %w(show)
  
  def index
    products = Product.search(params)
    render json: products, status: :ok
  end

  def show
    render json: @product, status: :ok
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true)
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to inventory_index_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:code, :name, :model, :description, :list_price, :stock, :min_stock, :credit_price, :cost_price, :provider_id, :product_brand_id, :product_category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.slim
= simple_form_for @product, html: { class: 'default' } do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs.flex.gap-5.w-full
    div.flex.flex-col
      = f.input :code, label: 'Código'
      = f.input :name, label: 'Artículo'
      = f.input :model, label: 'Modelo'
      = f.input :list_price, label: 'Precio Lista'
      = f.association :product_category, label: 'Categoría'
      = f.association :product_brand, label: 'Marca'
      = f.association :provider, label: 'Proveedor', label_method: :full_name
    div.flex.flex-col.justify-between
      div
        = f.input :description, label: 'Descripción', input_html: {rows: 6}
        .flex.gap-5
          = f.input :stock
          = f.input :min_stock, label: 'Stock Minimo'
        .flex.gap-5
          = f.input :cost_price, label: 'Precio Costo', disabled: true
          = f.input :credit_price, label: 'Precio Crédito', disabled: true
      div
        .form-actions
          = f.button :submit

app/views/products/_table.html.slim
h1.text-xl.font-bold Lista de Productos

= link_to '+ Nuevo Artículo', new_product_path, class: 'float-right bg-green-600 text-white px-3 rounded visited:text-white'

table.w-full.table-fixed
  thead.bg-gray-200
    tr.text-gray-500
      th width="150" Código
      th Artículo
      th Marca
      th Descripción
      th.text-right Precio Lista
      th.text-right Precio Costo
      th.text-center width="100" Stock
      th Proveedor
      th

  tbody
    - products.each do |product|
      tr.even:bg-gray-100.hover:bg-gray-600.hover:text-white
        td.text-center = product.code
        td = product.name
        td = product.product_brand&.name
        td = product.description
        td.text-right = number_to_currency(product.list_price)
        td.text-right = number_to_currency(product.cost_price)
        td.text-center = product.stock
        td.text-center = product.provider&.full_name
        td
          = link_to 'Ver', product
          =<> "|"
          = link_to 'Editar', edit_product_path(product)
          =<> "|"
          = link_to 'Eliminar', product, data: { confirm: 'Are you sure?' }, method: :delete

br

app/views/products/_table_min_stock.html.slim
table.w-full.table-fixed
  thead.bg-gray-200
    tr.text-gray-500
      th.text-center width="120" Código
      th.text-center Articulo
      th.text-center Marca
      th.text-center width="200" Modelo
      th.text-center Categoría
      th width="120" Stock

  tbody
    - products.each do |product|
      tr.even:bg-gray-100
        td.text-center.py-2.px-4 = product.code
        td.text-center = product.name
        td.text-center = product.product_brand&.name
        td.text-center = product.model
        td.text-center = product.product_category&.name
        td.text-center.px-3 
          = product.stock
          small.text-gray-400
            =< "(min #{product.min_stock})"
br

app/views/products/edit.html.slim
.bg-white.m-16.p-5.rounded-lg.shadow.xl:w-1/2.xl:mx-auto
  h1.font-bold.text-lg.mb-4 Editar Artículo
  hr.mb-4

  == render 'form'

  => link_to 'Show', @product
  '|
  =< link_to 'Back', products_path

app/views/products/new.html.slim
.bg-white.m-16.p-5.rounded-lg.shadow.xl:w-1/2.xl:mx-auto
  h1.font-bold.text-lg.mb-4 Agregar Artículo
  hr.mb-4

  == render 'form'

  = link_to 'Back', products_path

app/views/products/show.html.slim
.bg-white.m-16.p-5.rounded-lg.shadow

  .flex.mb-4.gap-10
    .flex.flex-col
      p.text-xl
        strong Articulo:
        =< @product.name
      p
        strong Código:
        =<> @product.code
        strong Modelo:
        =<> @product.model
      p
        strong Marca:
        =< @product.product_brand.name
      p
        strong Categoría:
        =< @product.product_category.name
      p
        strong Descripción:
        =< @product.description
      p
        strong Proveedor:
        =< @product.provider.full_name
    .flex.flex-col
      p
        strong Stock:
        =< @product.stock
      p
        strong Stock minimo:
        =< @product.min_stock
      p
        strong Precio Lista:
        =< number_to_currency @product.list_price
      p
        strong Precio Crédito:
        =< number_to_currency @product.credit_price
      p
        strong Precio Costo:
        =< number_to_currency @product.cost_price

  => link_to 'Atrás', inventory_index_path
  '|
  =< link_to 'Editar', edit_product_path(@product)